apiVersion: v1
kind: ConfigMap
metadata:
  name: dead-mans-switch-config-t13uziow
  namespace: monitoring
data:
  config.yaml: |2-

    interval: 5m
    notify:
      pagerduty:
        key: <YOUR_PAGERDUTY_KEY>
      slack:
        webhookurl: <YOUR_SLACK_WEBHOOK_URL>